pipeline:
  tasks:
  - name: package
    taskRef:
      resolver: git
      params:
      - { name: url, value: https://github.com/opendevstack/ods-pipeline-image.git }
      - { name: revision, value: v0.3.0 }
      - { name: pathInRepo, value: tasks/package.yaml }
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: deploy
    taskRef:
      resolver: git
      params:
      - { name: url, value: https://github.com/opendevstack/ods-pipeline-helm.git }
      - { name: revision, value: v0.4.1 }
      - { name: pathInRepo, value: tasks/deploy.yaml }
    runAfter:
    - package
    params:
    - name: namespace
      value: {{ cookiecutter.__project_slug }}-dev
    workspaces:
    - name: source
      workspace: shared-workspace
