branchToEnvironmentMapping:
- branch: '*'
  environment: dev

environments:
- name: dev
  namespace: @project@-dev
  stage: dev

pipeline:
  tasks:
  - name: package
    taskRef:
      kind: Task
      name: ods-package-image-v0-3-0
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: deploy
    taskRef:
      kind: Task
      name: ods-deploy-helm-v0-3-0
    runAfter:
    - package
    workspaces:
    - name: source
      workspace: shared-workspace
