branchToEnvironmentMapping:
- branch: '*'
  environment: dev

environments:
- name: dev
  namespace: {{cookiecutter.__project_slug}}-dev
  stage: dev

pipeline:
  tasks:
  - name: deploy
    taskRef:
      kind: Task
      name: ods-deploy-helm{{cookiecutter.task_suffix}}
    workspaces:
    - name: source
      workspace: shared-workspace
